version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - dupl
    - goconst
    - gocyclo
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - copyloopvar
    - ginkgolinter
    - gosec
    - asciicheck

linters-settings:
  revive:
    rules:
      - name: comment-spacings

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll

run:
  timeout: 5m
  allow-parallel-runners: true