# permissions for end users to view policymanifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: policymanifest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: policy-api
    app.kubernetes.io/part-of: policy-api
    app.kubernetes.io/managed-by: kustomize
  name: policymanifest-viewer-role
rules:
- apiGroups:
  - policy.giantswarm.io
  resources:
  - policymanifests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.giantswarm.io
  resources:
  - policymanifests/status
  verbs:
  - get
